---
- name: Allow HTTP and HTTPS on Ubuntu
  ansible.builtin.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - 80
    - 443
  when: ansible_distribution == 'Ubuntu'

- name: Allow HTTP and HTTPS on Fedora
  ansible.builtin.firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  loop:
    - http
    - https
  when: ansible_distribution == 'Fedora'

- name: Enable UFW on Ubuntu
  ansible.builtin.ufw:
    state: enabled
  when: ansible_distribution == 'Ubuntu'

- name: Enable firewalld on Fedora
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: yes
  when: ansible_distribution == 'Fedora'